window.EVERCADE_CATALOG = [
['console',1,'Atari Collection 1'],['console',2,'Namco Museum Collection 1'],['console',3,'Data East Collection 1'],['console',4,'Interplay Collection 1'],['console',5,'Atari Collection 2'],['console',6,'Namco Museum Collection 2'],['console',7,'Interplay Collection 2'],['console',8,'Mega Cat Studios Collection 1'],['console',9,'Piko Interactive Collection 1'],['console',10,'Technōs Collection 1'],['console',11,'Xeno Crisis & Tanglewood'],['console',12,'The Oliver Twins Collection'],['console',13,'Atari Lynx Collection 1'],['console',14,'Atari Lynx Collection 2'],['console',15,'Jaleco Collection 1'],['console',16,'Piko Collection 2'],['console',17,'Indie Heroes Collection 1'],['console',18,'Worms Collection 1'],['console',19,'Codemasters Collection 1'],['console',20,'Mega Cat Studios Collection 2'],['console',21,'Intellivision Collection 1'],['console',22,'The Bitmap Brothers Collection 1'],['console',23,'Renovation Collection 1'],['console',24,'Gremlin Collection 1'],['console',25,'Morphcat Games Collection 1'],['console',26,'Intellivision Collection 2'],['console',27,'Alwa’s Awakening / Cathedral'],['console',28,'Indie Heroes Collection 2'],['console',29,'Piko Collection 3'],['console',30,'The Sydney Hunter Collection'],['console',31,'Sunsoft Collection 1'],['console',32,'Full Void'],['console',33,'Duke Nukem Collection 1'],['console',34,'Duke Nukem Collection 2'],['console',35,'Goodboy Galaxy / Witch n’ Wiz'],['console',36,'Demons of Asteborg / Astebros'],['console',37,'Indie Heroes Collection 3'],['console',38,'Sunsoft Collection 2'],['console',39,'Piko Collection 4'],['console',40,'Tomb Raider Collection 1'],['console',41,'Legacy of Kain Collection'],['console',42,'Metal Dragon / Life on Mars'],['console',43,'Indie Heroes Collection 4'],['console',44,'Broken Sword Collection'],['console',45,'Tomb Raider Collection 2'],['console',46,'Gremlin Collection 2'],['console',47,'Activision Collection 1'],['console',48,'Rare Collection 1'],['console',49,'The Turrican Collection'],['console',50,'Activision Collection 2'],['console',51,'Mega Cat Studios Collection 3'],['console',52,'Activision Collection 3'],['console',53,'Banjo-Kazooie Double Pack'],
['arcade',1,'Technōs Arcade 1'],['arcade',2,'Data East Arcade 1'],['arcade',3,'Gaelco Arcade 1'],['arcade',4,'Atari Arcade 1'],['arcade',5,'Jaleco Arcade 1'],['arcade',6,'Gaelco Arcade 2'],['arcade',7,'Irem Arcade 1'],['arcade',8,'Toaplan Arcade 1'],['arcade',9,'Toaplan Arcade 2'],['arcade',10,'Piko Interactive Arcade 1'],['arcade',11,'Toaplan Arcade 3'],['arcade',12,'Data East Arcade 2'],['arcade',13,'Toaplan Arcade 4'],['arcade',14,'Atari Arcade 2'],['arcade',15,'Windjammers, Karnov & Friends'],['arcade',16,'NEOGEO Arcade 1'],['arcade',17,'TAITO Arcade 1'],['arcade',18,'TAITO Arcade 2'],['arcade',19,'NEOGEO Arcade 2'],['arcade',20,'NEOGEO Arcade 3'],['arcade',21,'TAITO Arcade 3'],['arcade',22,'NEOGEO Arcade 4'],['arcade',23,'Visco Arcade 1'],['arcade',24,'Visco Arcade 2'],
['computer',1,'THEC64 Collection 1'],['computer',2,'THEC64 Collection 2'],['computer',3,'Team17 Collection 1'],['computer',4,'Delphine Software Collection 1'],['computer',5,'Home Computer Heroes Collection 1'],['computer',6,'THEC64 Collection 3'],['computer',7,'Thalamus Collection 1'],['computer',8,'The Bitmap Brothers Collection 2'],['computer',9,'Roguecraft DX'],['computer',10,'The Llamasoft Collection']
].map(([series,number,title])=>({
  key:`${series}-${number}`,
  series,
  number,
  title,
  image:`assets/cartridges/${series}-${String(number).padStart(2,'0')}.webp`
}));
