(() => {
  'use strict';
  const catalog=window.EVERCADE_CATALOG||[];
  const sprite=String(window.EVERCADE_SPRITE_150||'');
  const indexFor=x=>x.series==='arcade'?(x.number-1):x.series==='computer'?(24+x.number-1):(34+x.number-1);
  const byTitle=new Map(catalog.map(x=>[x.title.trim().toLowerCase(),x]));
  const cover=x=>{const i=indexFor(x),c=i%10,r=Math.floor(i/10);const el=document.createElement('div');el.className='v150-cover';el.setAttribute('aria-hidden','true');el.style.setProperty('--sx',`${(c*100/9).toFixed(6)}%`);el.style.setProperty('--sy',`${(r*100/8).toFixed(6)}%`);return el;};
  const findCartridge=card=>{const a=card.querySelector('.eyebrow')?.textContent?.trim()?.toLowerCase();const h=card.querySelector('h3')?.textContent?.trim()?.toLowerCase();return byTitle.get(a)||byTitle.get(h)||null;};
  const decorate=()=>{
    document.querySelectorAll('#collectionList .card,#catalogList .card,#automaticDeals .card').forEach(card=>{
      if(card.dataset.v150Decorated)return;const x=findCartridge(card);const main=card.querySelector('.card-main');if(!x||!main)return;
      const wrap=document.createElement('div');wrap.className='v150-card-layout';wrap.append(cover(x));main.parentNode.insertBefore(wrap,main);wrap.append(main);card.dataset.v150Decorated='1';
    });
    document.querySelectorAll('#collectionList .card-actions').forEach(el=>el.hidden=true);
  };
  const style=document.createElement('style');style.id='evercade-v150-ui';
  style.textContent=`html,body{max-width:100%;overflow-x:hidden}.topbar,.tabs{position:static!important;top:auto!important}.tabs{overflow-x:hidden!important;display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:6px!important}.tabs button{min-width:0!important;padding:10px 6px!important;white-space:normal!important}.v150-card-layout{display:grid;grid-template-columns:82px minmax(0,1fr);gap:14px;align-items:center;min-width:0}.v150-cover{width:82px;aspect-ratio:3/4;border:1px solid #303948;border-radius:10px;background-color:#0d1118;background-image:url("data:image/webp;base64,${sprite}");background-repeat:no-repeat;background-size:1000% 900%;background-position:var(--sx) var(--sy);box-shadow:0 8px 22px rgba(0,0,0,.28)}#collectionList .card{padding:12px 12px 12px 16px}#collectionList .card-main{display:block!important}#collectionList .card-actions{display:none!important}.card,.card-main,.v150-card-layout,.deal-center,.deal-center-grid,.deal-filter-grid{min-width:0;max-width:100%}.card h3,.card p,.source-link,.deal-history{overflow-wrap:anywhere;word-break:break-word}.progress-panel{padding:14px 16px!important;grid-template-columns:1fr auto!important}.progress-panel .eyebrow{font-size:.68rem}.progress-panel h2{font-size:1.25rem}.progress-panel>strong{font-size:2rem!important}.progress-panel .progress-track{height:10px!important;margin-top:12px!important}@media(max-width:720px){main{padding:12px!important}.topbar{padding:16px 14px!important;gap:10px}.topbar h1{font-size:1.45rem!important}.header-tools{gap:7px!important}.header-tools .button,.version-pill{padding:8px 10px!important}.stats article{padding:16px!important}.stats strong{font-size:1.55rem!important}.panel{padding:14px!important;margin-top:12px!important}.v150-card-layout{grid-template-columns:68px minmax(0,1fr);gap:11px}.v150-cover{width:68px;border-radius:8px}.card{padding:12px 12px 12px 16px!important}.card-actions{gap:6px!important;justify-content:flex-start!important}.card-actions button,.card-actions .button{padding:7px 9px!important}.deal-filter-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.deal-center-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:430px){.topbar{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important}.topbar h1{font-size:1.3rem!important}.topbar p{font-size:.88rem}.tabs button{font-size:.82rem!important;padding:9px 3px!important}.v150-card-layout{grid-template-columns:60px minmax(0,1fr);gap:10px}.v150-cover{width:60px}.deal-filter-grid{grid-template-columns:1fr!important}}@media(max-width:380px){.tabs button{font-size:.76rem!important}.v150-card-layout{grid-template-columns:54px minmax(0,1fr)}.v150-cover{width:54px}}`;
  document.head.appendChild(style);decorate();new MutationObserver(decorate).observe(document.querySelector('main')||document.body,{subtree:true,childList:true});window.EVERCADE_UI_150=Object.freeze({version:'1.5.0',spriteEntries:87,decorate});
})();
